# Standalone exhaustive test for the booth_mult8 arithmetic unit.
#   make -f Makefile.booth
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src
SIM_BUILD = sim_build/booth

VERILOG_SOURCES += $(SRC_DIR)/project.v
COMPILE_ARGS    += -I$(SRC_DIR)

TOPLEVEL = booth_mult8
COCOTB_TEST_MODULES = test_booth

include $(shell cocotb-config --makefiles)/Makefile.sim
